# Databricks notebook source
# DBTITLE 1,Notebook Summary
# MAGIC %md
# MAGIC ## DLT — Silver SCD2 Dimensions
# MAGIC
# MAGIC Delta Live Tables pipeline replacing the four manual 6-step silver SCD2 notebooks.
# MAGIC Each dimension produces two tables via `dp.create_auto_cdc_flow()`:
# MAGIC
# MAGIC | Source bronze table | SCD2 history | SCD1 current (Power BI) |
# MAGIC |---|---|---|
# MAGIC | `{bronze_schema}.lakeflow_jobs` | `td_lakeflow_job_history` | `td_lakeflow_job` |
# MAGIC | `{bronze_schema}.lakeflow_pipelines` | `td_lakeflow_pipeline_history` | `td_lakeflow_pipeline` |
# MAGIC | `{bronze_schema}.compute_clusters` | `td_compute_cluster_history` | `td_compute_cluster` |
# MAGIC | `{bronze_schema}.compute_warehouses` | `td_compute_warehouse_history` | `td_compute_warehouse` |
# MAGIC
# MAGIC **DLT pipeline configuration (Databricks UI):**
# MAGIC - Target catalog: `{catalog_name}_{catalog_env}`
# MAGIC - Target schema: `global_it_hub`
# MAGIC - Pipeline parameters: `pipeline.catalog_name`, `pipeline.catalog_env`, `pipeline.schema_bronze`
# MAGIC
# MAGIC **Surrogate keys:** each table's `dp.create_streaming_table()` call (below) declares
# MAGIC the schema with `GENERATED BY DEFAULT AS IDENTITY`. DLT `create_auto_cdc_flow()` targets that
# MAGIC schema — Delta auto-assigns surrogate key values on INSERT, existing rows keep their
# MAGIC keys on UPDATE. Sentinel rows (-2/-1) are inserted once by `init_post_dlt_silver.sql`
# MAGIC and are never touched by DLT (their natural keys never appear in real dimension data).
# MAGIC
# MAGIC **First-time setup:**
# MAGIC 1. Trigger a full-refresh run of the silver pipeline (`resources/pipelines.yml`) — DLT creates the tables
# MAGIC 2. Run `init_post_dlt_silver.sql` as a regular notebook to insert sentinel rows
# MAGIC
# MAGIC Each table's `dp.create_streaming_table()` declaration sits immediately before the
# MAGIC `create_auto_cdc_flow()`/`@dp.table` that populates it — DLT failed to resolve the flow
# MAGIC when the declaration lived in a separate notebook, even though both were libraries on the
# MAGIC same pipeline.

# COMMAND ----------

from pyspark import pipelines as dp
from pyspark.sql.functions import col, when, from_json, current_timestamp

# Pipeline parameters — set in the DLT pipeline configuration UI
catalog_name = spark.conf.get("pipeline.catalog_name", "it_security")
catalog_env  = spark.conf.get("pipeline.catalog_env",  "dev")
catalog      = f"{catalog_name}_{catalog_env}"
bronze_schema    = spark.conf.get("pipeline.schema_bronze", "databricks")

_silver = {"quality": "silver"}

# COMMAND ----------

# DBTITLE 1,JOBS — Source view (column renames)
@dp.view(name="v_bz_lakeflow_jobs")
def v_bz_lakeflow_jobs():
    return (
        spark.readStream.option("skipChangeCommits", "true")
        .table(f"{catalog}.{bronze_schema}.lakeflow_jobs")
        .select(
            col("account_id").alias("account_cd"),
            col("region").alias("region_lb"),
            col("workspace_id").alias("workspace_cd"),
            col("job_id").alias("job_cd"),
            col("name").alias("job_name_lb"),
            col("description").alias("description_lb"),
            col("creator_user_name").alias("creator_userid_cd"),
            col("create_time").alias("create_dt"),
            col("run_as").alias("run_as_cd"),
            col("run_as_user_name").alias("run_as_user_lb"),
            from_json(col("tags"), "map<string,string>").alias("tags"),
            col("change_time"),
            when(col("delete_time").isNotNull(), 1).otherwise(0).alias("is_deleted_fl"),
            col("delete_time").alias("delete_dt"),
            current_timestamp().alias("sys_load_dt"),
        )
    )

# COMMAND ----------

# DBTITLE 1,JOBS — SCD2 history (all versions)
dp.create_streaming_table("td_lakeflow_job_history", table_properties=_silver,
    comment="SCD2 history of Lakeflow jobs — one row per validity period (change_time to next change_time).")

dp.create_auto_cdc_flow(
    target             = "td_lakeflow_job_history",
    source             = "v_bz_lakeflow_jobs",
    keys               = ["account_cd", "workspace_cd", "job_cd"],
    sequence_by        = col("change_time"),
    stored_as_scd_type = 2,
)

# COMMAND ----------

# DBTITLE 1,JOBS — SCD1 current (Power BI dimension)
dp.create_streaming_table("td_lakeflow_job", table_properties=_silver,
    comment="Current state (SCD1) of Lakeflow jobs — one row per job.",
    schema="""
    job_id            BIGINT    GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) COMMENT 'Surrogate key.',
    account_cd        STRING    NOT NULL COMMENT 'Databricks account UUID.',
    region_lb         STRING    COMMENT 'Databricks region (e.g. eastus, westeurope).',
    workspace_cd   STRING    NOT NULL COMMENT 'Workspace ID the job belongs to.',
    job_cd         STRING    NOT NULL COMMENT 'Natural key — system tables job_id.',
    job_name_lb       STRING    COMMENT 'Job display name.',
    description_lb    STRING    COMMENT 'Job description.',
    creator_userid_cd STRING    COMMENT 'User ID of the job creator.',
    create_dt         TIMESTAMP COMMENT 'Job creation timestamp.',
    run_as_cd         STRING    COMMENT 'Identity (user or service principal) the job runs as.',
    run_as_user_lb    STRING    COMMENT 'Display name of the run_as identity, when a user.',
    tags              MAP<STRING, STRING> COMMENT 'Job tags as key/value pairs.',
    change_time       TIMESTAMP COMMENT 'Timestamp of the last change recorded for this job in system tables.',
    is_deleted_fl     INT       COMMENT 'Flag: 1 if the job has been deleted, 0 otherwise.',
    delete_dt         TIMESTAMP COMMENT 'Timestamp the job was deleted, if applicable.',
    sys_load_dt       TIMESTAMP COMMENT 'Pipeline audit — timestamp DLT last (re)computed this row. create_auto_cdc_flow() has no insert-only column semantics, so this is re-stamped on every update too, same as sys_load_dt on fact tables — not a true first-insert time.'
""")

dp.create_auto_cdc_flow(
    target             = "td_lakeflow_job",
    source             = "v_bz_lakeflow_jobs",
    keys               = ["account_cd", "workspace_cd", "job_cd"],
    sequence_by        = col("change_time"),
    stored_as_scd_type = 1,
)

# COMMAND ----------

# DBTITLE 1,PIPELINES — Source view (column renames)
@dp.view(name="v_bz_lakeflow_pipelines")
def v_bz_lakeflow_pipelines():
    return (
        spark.readStream.option("skipChangeCommits", "true")
        .table(f"{catalog}.{bronze_schema}.lakeflow_pipelines")
        .select(
            col("account_id").alias("account_cd"),
            col("region").alias("region_lb"),
            col("workspace_id").alias("workspace_cd"),
            col("pipeline_id").alias("pipeline_cd"),
            col("pipeline_type").alias("pipeline_type_lb"),
            col("name").alias("pipeline_name_lb"),
            col("created_by").alias("created_by_cd"),
            col("create_time").alias("create_dt"),
            col("run_as").alias("run_as_cd"),
            from_json(col("tags"), "map<string,string>").alias("tags"),
            from_json(col("configuration"), "map<string,string>").alias("configuration"),
            col("change_time"),
            when(col("delete_time").isNotNull(), 1).otherwise(0).alias("is_deleted_fl"),
            col("delete_time").alias("delete_dt"),
            current_timestamp().alias("sys_load_dt"),
        )
    )

# COMMAND ----------

# DBTITLE 1,PIPELINES — SCD2 history
dp.create_streaming_table("td_lakeflow_pipeline_history", table_properties=_silver,
    comment="SCD2 history of Lakeflow (DLT) pipelines — one row per validity period (change_time to next change_time).")

dp.create_auto_cdc_flow(
    target             = "td_lakeflow_pipeline_history",
    source             = "v_bz_lakeflow_pipelines",
    keys               = ["account_cd", "workspace_cd", "pipeline_cd"],
    sequence_by        = col("change_time"),
    stored_as_scd_type = 2,
)

# COMMAND ----------

# DBTITLE 1,PIPELINES — SCD1 current
dp.create_streaming_table("td_lakeflow_pipeline", table_properties=_silver,
    comment="Current state (SCD1) of Lakeflow (DLT) pipelines — one row per pipeline.",
    schema="""
    pipeline_id      BIGINT    GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) COMMENT 'Surrogate key.',
    account_cd       STRING    NOT NULL COMMENT 'Databricks account UUID.',
    region_lb        STRING    COMMENT 'Databricks region (e.g. eastus, westeurope).',
    workspace_cd  STRING    NOT NULL COMMENT 'Workspace ID the pipeline belongs to.',
    pipeline_cd   STRING    NOT NULL COMMENT 'Natural key — system tables pipeline_id.',
    pipeline_type_lb STRING    COMMENT 'Pipeline type (e.g. WORKSPACE, MANAGED_INGESTION).',
    pipeline_name_lb STRING    COMMENT 'Pipeline display name.',
    created_by_cd    STRING    COMMENT 'User ID of the pipeline creator.',
    create_dt        TIMESTAMP COMMENT 'Pipeline creation timestamp.',
    run_as_cd        STRING    COMMENT 'Identity (user or service principal) the pipeline runs as.',
    tags             MAP<STRING, STRING> COMMENT 'Pipeline tags as key/value pairs.',
    configuration    MAP<STRING, STRING> COMMENT 'Pipeline configuration settings as key/value pairs.',
    change_time      TIMESTAMP COMMENT 'Timestamp of the last change recorded for this pipeline in system tables.',
    is_deleted_fl    INT       COMMENT 'Flag: 1 if the pipeline has been deleted, 0 otherwise.',
    delete_dt        TIMESTAMP COMMENT 'Timestamp the pipeline was deleted, if applicable.',
    sys_load_dt      TIMESTAMP COMMENT 'Pipeline audit — timestamp DLT last (re)computed this row. create_auto_cdc_flow() has no insert-only column semantics, so this is re-stamped on every update too, same as sys_load_dt on fact tables — not a true first-insert time.'
""")

dp.create_auto_cdc_flow(
    target             = "td_lakeflow_pipeline",
    source             = "v_bz_lakeflow_pipelines",
    keys               = ["account_cd", "workspace_cd", "pipeline_cd"],
    sequence_by        = col("change_time"),
    stored_as_scd_type = 1,
)

# COMMAND ----------

# DBTITLE 1,CLUSTERS — Source view (column renames)
@dp.view(name="v_bz_compute_clusters")
def v_bz_compute_clusters():
    return (
        spark.readStream.option("skipChangeCommits", "true")
        .table(f"{catalog}.{bronze_schema}.compute_clusters")
        .select(
            col("account_id").alias("account_cd"),
            col("region").alias("region_lb"),
            col("workspace_id").alias("workspace_cd"),
            col("cluster_id").alias("cluster_cd"),
            col("cluster_name").alias("cluster_name_lb"),
            col("owned_by").alias("owned_by_cd"),
            col("create_time").alias("create_dt"),
            col("cluster_source").alias("cluster_source_lb"),
            col("dbr_version").alias("dbr_version_lb"),
            col("driver_node_type").alias("driver_node_type_lb"),
            col("worker_node_type").alias("worker_node_type_lb"),
            col("worker_count").alias("worker_count_nb"),
            col("min_autoscale_workers").alias("min_autoscale_workers_nb"),
            col("max_autoscale_workers").alias("max_autoscale_workers_nb"),
            col("auto_termination_minutes").alias("auto_termination_minutes_nb"),
            when(col("enable_elastic_disk"), 1).otherwise(0).alias("enable_elastic_disk_fl"),
            col("driver_instance_pool_id").alias("driver_instance_pool_cd"),
            col("worker_instance_pool_id").alias("worker_instance_pool_cd"),
            col("data_security_mode").alias("data_security_mode_lb"),
            col("policy_id").alias("policy_cd"),
            from_json(col("tags"), "map<string,string>").alias("tags"),
            col("change_time"),
            when(col("delete_time").isNotNull(), 1).otherwise(0).alias("is_deleted_fl"),
            col("delete_time").alias("delete_dt"),
            current_timestamp().alias("sys_load_dt"),
        )
    )

# COMMAND ----------

# DBTITLE 1,CLUSTERS — SCD2 history
dp.create_streaming_table("td_compute_cluster_history", table_properties=_silver,
    comment="SCD2 history of compute clusters — one row per validity period (change_time to next change_time).")

dp.create_auto_cdc_flow(
    target             = "td_compute_cluster_history",
    source             = "v_bz_compute_clusters",
    keys               = ["account_cd", "workspace_cd", "cluster_cd"],
    sequence_by        = col("change_time"),
    stored_as_scd_type = 2,
)

# COMMAND ----------

# DBTITLE 1,CLUSTERS — SCD1 current
dp.create_streaming_table("td_compute_cluster", table_properties=_silver,
    comment="Current state (SCD1) of compute clusters — one row per cluster.",
    schema="""
    cluster_id                  BIGINT    GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) COMMENT 'Surrogate key.',
    account_cd                  STRING    NOT NULL COMMENT 'Databricks account UUID.',
    region_lb                   STRING    COMMENT 'Databricks region (e.g. eastus, westeurope).',
    workspace_cd             STRING    NOT NULL COMMENT 'Workspace ID the cluster belongs to.',
    cluster_cd               STRING    NOT NULL COMMENT 'Natural key — system tables cluster_id.',
    cluster_name_lb             STRING    COMMENT 'Cluster display name.',
    owned_by_cd                 STRING    COMMENT 'User or service principal ID that owns the cluster.',
    create_dt                   TIMESTAMP COMMENT 'Cluster creation timestamp.',
    cluster_source_lb           STRING    COMMENT 'Cluster source (e.g. UI, JOB, API).',
    dbr_version_lb              STRING    COMMENT 'Databricks Runtime version.',
    driver_node_type_lb         STRING    COMMENT 'Driver node instance type.',
    worker_node_type_lb         STRING    COMMENT 'Worker node instance type.',
    worker_count_nb             BIGINT    COMMENT 'Fixed worker count (when autoscaling is disabled).',
    min_autoscale_workers_nb    BIGINT    COMMENT 'Minimum worker count for autoscaling.',
    max_autoscale_workers_nb    BIGINT    COMMENT 'Maximum worker count for autoscaling.',
    auto_termination_minutes_nb BIGINT    COMMENT 'Idle minutes before the cluster auto-terminates.',
    enable_elastic_disk_fl      INT       COMMENT 'Flag: 1 if elastic disk (autoscaling local storage) is enabled, 0 otherwise.',
    driver_instance_pool_cd  STRING    COMMENT 'Instance pool ID used for the driver node, if any.',
    worker_instance_pool_cd  STRING    COMMENT 'Instance pool ID used for worker nodes, if any.',
    data_security_mode_lb       STRING    COMMENT 'Cluster data security / access mode.',
    policy_cd                STRING    COMMENT 'Cluster policy ID applied to the cluster, if any.',
    tags                        MAP<STRING, STRING> COMMENT 'Cluster tags as key/value pairs.',
    change_time                 TIMESTAMP COMMENT 'Timestamp of the last change recorded for this cluster in system tables.',
    is_deleted_fl               INT       COMMENT 'Flag: 1 if the cluster has been deleted, 0 otherwise.',
    delete_dt                   TIMESTAMP COMMENT 'Timestamp the cluster was deleted, if applicable.',
    sys_load_dt                 TIMESTAMP COMMENT 'Pipeline audit — timestamp DLT last (re)computed this row. create_auto_cdc_flow() has no insert-only column semantics, so this is re-stamped on every update too, same as sys_load_dt on fact tables — not a true first-insert time.'
""")

dp.create_auto_cdc_flow(
    target             = "td_compute_cluster",
    source             = "v_bz_compute_clusters",
    keys               = ["account_cd", "workspace_cd", "cluster_cd"],
    sequence_by        = col("change_time"),
    stored_as_scd_type = 1,
)

# COMMAND ----------

# DBTITLE 1,WAREHOUSES — Source view (column renames)
@dp.view(name="v_bz_compute_warehouses")
def v_bz_compute_warehouses():
    return (
        spark.readStream.option("skipChangeCommits", "true")
        .table(f"{catalog}.{bronze_schema}.compute_warehouses")
        .select(
            col("account_id").alias("account_cd"),
            col("region").alias("region_lb"),
            col("workspace_id").alias("workspace_cd"),
            col("warehouse_id").alias("warehouse_cd"),
            col("warehouse_name").alias("warehouse_name_lb"),
            col("warehouse_type").alias("warehouse_type_lb"),
            col("warehouse_channel").alias("warehouse_channel_lb"),
            col("warehouse_size").alias("warehouse_size_lb"),
            col("min_clusters").alias("min_clusters_nb"),
            col("max_clusters").alias("max_clusters_nb"),
            col("auto_stop_minutes").alias("auto_stop_minutes_nb"),
            from_json(col("tags"), "map<string,string>").alias("tags"),
            col("change_time"),
            col("created_by").alias("created_by_cd"),
            when(col("delete_time").isNotNull(), 1).otherwise(0).alias("is_deleted_fl"),
            col("delete_time").alias("delete_dt"),
            current_timestamp().alias("sys_load_dt"),
        )
    )

# COMMAND ----------

# DBTITLE 1,WAREHOUSES — SCD2 history
dp.create_streaming_table("td_compute_warehouse_history", table_properties=_silver,
    comment="SCD2 history of SQL warehouses — one row per validity period (change_time to next change_time).")

dp.create_auto_cdc_flow(
    target             = "td_compute_warehouse_history",
    source             = "v_bz_compute_warehouses",
    keys               = ["account_cd", "workspace_cd", "warehouse_cd"],
    sequence_by        = col("change_time"),
    stored_as_scd_type = 2,
)

# COMMAND ----------

# DBTITLE 1,WAREHOUSES — SCD1 current
dp.create_streaming_table("td_compute_warehouse", table_properties=_silver,
    comment="Current state (SCD1) of SQL warehouses — one row per warehouse.",
    schema="""
    warehouse_id         BIGINT    GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) COMMENT 'Surrogate key.',
    account_cd           STRING    NOT NULL COMMENT 'Databricks account UUID.',
    region_lb           STRING    COMMENT 'Databricks region (e.g. eastus, westeurope).',
    workspace_cd      STRING    NOT NULL COMMENT 'Workspace ID the warehouse belongs to.',
    warehouse_cd      STRING    NOT NULL COMMENT 'Natural key — system tables warehouse_id.',
    warehouse_name_lb    STRING    COMMENT 'Warehouse display name.',
    created_by_cd        STRING    COMMENT 'User ID of the warehouse creator.',
    warehouse_type_lb    STRING    COMMENT 'Warehouse type (e.g. PRO, CLASSIC, SERVERLESS).',
    warehouse_channel_lb STRING    COMMENT 'Release channel (e.g. CHANNEL_NAME_CURRENT, CHANNEL_NAME_PREVIEW).',
    warehouse_size_lb    STRING    COMMENT 'Warehouse cluster size (e.g. X-Small, Medium).',
    min_clusters_nb      INT       COMMENT 'Minimum number of clusters for autoscaling.',
    max_clusters_nb      INT       COMMENT 'Maximum number of clusters for autoscaling.',
    auto_stop_minutes_nb INT       COMMENT 'Idle minutes before the warehouse auto-stops.',
    tags                 MAP<STRING, STRING> COMMENT 'Warehouse tags as key/value pairs.',
    change_time          TIMESTAMP COMMENT 'Timestamp of the last change recorded for this warehouse in system tables.',
    is_deleted_fl        INT       COMMENT 'Flag: 1 if the warehouse has been deleted, 0 otherwise.',
    delete_dt            TIMESTAMP COMMENT 'Timestamp the warehouse was deleted, if applicable.',
    sys_load_dt          TIMESTAMP COMMENT 'Pipeline audit — timestamp DLT last (re)computed this row. create_auto_cdc_flow() has no insert-only column semantics, so this is re-stamped on every update too, same as sys_load_dt on fact tables — not a true first-insert time.'
""")

dp.create_auto_cdc_flow(
    target             = "td_compute_warehouse",
    source             = "v_bz_compute_warehouses",
    keys               = ["account_cd", "workspace_cd", "warehouse_cd"],
    sequence_by        = col("change_time"),
    stored_as_scd_type = 1,
)

# COMMAND ----------
