targets:
  # The 'dev' target, for development purposes. This target is the default.
  staging:
    presets:
      tags:
        AppId: "${var.app_id}"
        dataproduct: "${var.data_product}"
        domain: "${var.domain}"
    
    mode: production
    
    variables:
      catalog_env: staging

