-- Databricks notebook source
-- DBTITLE 1,Notebook Summary
-- MAGIC %md
-- MAGIC ## Silver — Init Tables
-- MAGIC
-- MAGIC One-time (or idempotent) setup notebook. Creates the silver tables **not** managed by
-- MAGIC a DLT pipeline. Safe to re-run: every statement uses `CREATE TABLE IF NOT EXISTS`.
-- MAGIC
-- MAGIC | Table | Populated by |
-- MAGIC |---|---|
-- MAGIC | `td_account` | Manually maintained |
-- MAGIC | `tf_billing_cost` | `silver_billing_cost.sql` |
-- MAGIC | `tr_resource_tag` | `silver_resource_tag.sql` |
-- MAGIC | `td_tag_key` | `silver_tag_key.sql` |
-- MAGIC | `td_workspace` | `silver_workspace.sql` |
-- MAGIC | `td_billing_list_price` | `silver_billing_cost.sql` |
-- MAGIC | `td_dbx_user` | `silver_identity.sql` |
-- MAGIC | `td_dbx_service_principal` | `silver_identity.sql` |
-- MAGIC | `td_identity` | `silver_identity.sql` |
-- MAGIC | `td_resource` | `silver_resource.sql` |
-- MAGIC
-- MAGIC DLT-managed tables (`td_lakeflow_job(_history)`, `td_lakeflow_pipeline(_history)`,
-- MAGIC `td_compute_cluster(_history)`, `td_compute_warehouse(_history)`,
-- MAGIC `tf_billing_usage`, `td_billing_app`,
-- MAGIC `td_billing_notebook`, `td_billing_endpoint`, `td_billing_network`) are declared by
-- MAGIC `dlt.create_streaming_table()` in `pipelines/silver/silver_dimensions.py` and
-- MAGIC `silver_billing.py` — their DDL is no longer created here. The original DDL (and the DROP
-- MAGIC cell needed before a DLT pipeline's first run, if these tables pre-exist as plain managed
-- MAGIC tables) is kept for reference in `legacy/silver/init_tables_silver_dlt_managed.sql`.
-- MAGIC
-- MAGIC Run this notebook **once before** the first execution of any silver load notebook,
-- MAGIC or after a schema/table is dropped and needs to be recreated.

-- COMMAND ----------

-- MAGIC %python
-- MAGIC dbutils.widgets.text("catalog_env", "dev")
-- MAGIC catalog_env = dbutils.widgets.get("catalog_env")
-- MAGIC
-- MAGIC dbutils.widgets.text("catalog_name", "it_security")
-- MAGIC catalog_name = dbutils.widgets.get("catalog_name")
-- MAGIC
-- MAGIC catalog = f"{catalog_name}_{catalog_env}"
-- MAGIC silver_schema = "global_it_hub"
-- MAGIC
-- MAGIC spark.sql(f"USE CATALOG {catalog}")
-- MAGIC spark.sql(f"USE SCHEMA {silver_schema}")

-- COMMAND ----------

-- DBTITLE 1,Drop non-DLT tables (run only when resetting the environment)
-- WARNING: drops tables managed by SQL notebooks.
-- Skip this cell on normal re-runs — only needed for full clean re-initialization.
DROP TABLE IF EXISTS global_it_hub.tr_resource_tag;
DROP TABLE IF EXISTS global_it_hub.tf_billing_cost;
DROP TABLE IF EXISTS global_it_hub.td_tag_key;
DROP TABLE IF EXISTS global_it_hub.td_account;
DROP TABLE IF EXISTS global_it_hub.td_workspace;
DROP TABLE IF EXISTS global_it_hub.td_billing_list_price;
DROP TABLE IF EXISTS global_it_hub.td_dbx_user;
DROP TABLE IF EXISTS global_it_hub.td_dbx_service_principal;
DROP TABLE IF EXISTS global_it_hub.td_identity;
DROP TABLE IF EXISTS global_it_hub.td_resource;

-- COMMAND ----------

-- DBTITLE 1,td_account
-- Account reference dimension: one row per Databricks account.
-- Manually maintained — add a row per account ingested into this catalog.
CREATE TABLE IF NOT EXISTS global_it_hub.td_account (
  account_id     BIGINT    GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) COMMENT 'Surrogate key — auto-assigned integer for Power BI relationships',
  account_cd     STRING    NOT NULL COMMENT 'Databricks account UUID — natural key',
  description_lb STRING             COMMENT 'Human-readable account description',
  -- Audit
  sys_create_dt  TIMESTAMP NOT NULL COMMENT 'When this row was first inserted',
  sys_update_dt  TIMESTAMP NOT NULL COMMENT 'When this row was last updated'
)
USING DELTA
COMMENT 'Account reference dimension. One row per Databricks account ingested into this catalog.'
TBLPROPERTIES ('quality' = 'silver');

-- COMMAND ----------

-- DBTITLE 1,td_account — known accounts
-- Idempotent insert: MERGE ensures re-running this cell does not duplicate rows.
-- Add one VALUES row per account as new accounts are onboarded.
MERGE INTO global_it_hub.td_account AS tgt
USING (
  VALUES
    ('9f336835-f3ce-4a17-b925-e2e1b67d8ffd', 'IPSEN AWS Databricks')
  AS src(account_cd, description_lb)
) ON tgt.account_cd = src.account_cd
WHEN NOT MATCHED THEN INSERT (account_cd, description_lb, sys_create_dt, sys_update_dt)
VALUES (src.account_cd, src.description_lb, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- COMMAND ----------

-- DBTITLE 1,tf_billing_cost
-- Silver fact table joining billing usage with list prices. One row per billing record.
-- Sourced from tf_billing_usage (silver) enriched with cost in USD from system.billing.list_prices.
-- Cluster by ingestion_dt — matches tf_billing_usage partitioning for efficient MERGE.
CREATE TABLE IF NOT EXISTS global_it_hub.tf_billing_cost (
  record_cd        STRING              NOT NULL COMMENT 'Unique billing record identifier (source: record_id)',
  account_cd          STRING              NOT NULL COMMENT 'Databricks account identifier',
  workspace_cd     STRING              NOT NULL COMMENT 'Databricks workspace identifier',
  record_type_lb      STRING              NOT NULL COMMENT 'Record category: ORIGINAL, RETRACTION, or RESTATEMENT',
  ingestion_dt      DATE                NOT NULL COMMENT 'Date when the record was published to the system table — partition key',
  usage_dt          DATE                NOT NULL COMMENT 'Date when the usage occurred',
  usage_start_dt      TIMESTAMP                    COMMENT 'Start timestamp of the usage period',
  usage_end_dt        TIMESTAMP                    COMMENT 'End timestamp of the usage period',
  product_lb          STRING                       COMMENT 'Billing origin product: JOBS, DLT, SQL, etc.',
  usage_type_lb       STRING                       COMMENT 'Usage category: COMPUTE_TIME, STORAGE_SPACE, etc.',
  sku_name_lb         STRING                       COMMENT 'SKU name',
  cloud_lb            STRING                       COMMENT 'Cloud provider: AWS, AZURE, or GCP',
  usage_unit_lb       STRING                       COMMENT 'Unit of measurement, e.g. DBU',
  usage_quantity_nb   DOUBLE                       COMMENT 'Amount of units consumed',
  custom_tags         MAP<STRING, STRING>           COMMENT 'User-defined tags on the resource',
  -- usage_metadata is omitted from the DDL: MERGE WITH SCHEMA EVOLUTION adds it automatically
  -- from tf_billing_usage on the first run, carrying the full struct without field restriction.
  run_as_cd           STRING                       COMMENT 'Identity that ran the resource (source: identity_metadata.run_as).',
  run_by_cd           STRING                       COMMENT 'Identity that triggered the run (source: identity_metadata.run_by).',
  created_by_cd       STRING                       COMMENT 'Identity that created the resource (source: identity_metadata.created_by).',
  owned_by_cd         STRING                       COMMENT 'Identity that owns the resource (source: identity_metadata.owned_by).',
  jobs_tier_lb        STRING                       COMMENT 'Jobs tier: CLASSIC or SERVERLESS',
  is_serverless_fl    INT                          COMMENT '1 = serverless compute, 0 = classic',
  is_photon_fl        INT                          COMMENT '1 = Photon engine enabled',
  line_cost_usd       DOUBLE                       COMMENT 'Estimated cost in USD: usage_quantity × list price (source: system.billing.list_prices)',
  usage_load_dt       TIMESTAMP                    COMMENT 'sys_load_dt of the source tf_billing_usage row — watermark basis (MAX drives incremental costing)',
  -- Audit
  sys_load_dt         TIMESTAMP           NOT NULL COMMENT 'When this row was last written by the pipeline'
)
USING DELTA
CLUSTER BY (ingestion_dt)
COMMENT 'Silver fact table of Databricks billable usage enriched with list price cost. One row per billing record.'
TBLPROPERTIES ('quality' = 'silver');

-- COMMAND ----------

-- DBTITLE 1,tr_resource_tag
-- Resource × tag key bridge table. One row per (resource_id, tag_key_id).
-- tag_key_id is an integer FK to td_tag_key — enables efficient Power BI relationships.
-- tag_value_lb holds the actual tag value, or 'Untagged' when the resource does not carry that key.
CREATE TABLE IF NOT EXISTS global_it_hub.tr_resource_tag (
  resource_id   BIGINT    NOT NULL COMMENT 'FK to td_resource.resource_id',
  tag_key_id    BIGINT    NOT NULL COMMENT 'FK to td_tag_key.tag_key_id — integer surrogate for Power BI join',
  tag_value_lb  STRING    NOT NULL COMMENT 'Actual tag value, or ''Untagged'' when the resource lacks this key',
  -- Audit
  sys_create_dt TIMESTAMP NOT NULL COMMENT 'When this row was first inserted by the pipeline',
  sys_update_dt TIMESTAMP NOT NULL COMMENT 'When this row was last written by the pipeline'
)
USING DELTA
COMMENT 'Resource × tag key bridge. One row per (resource, tag key). Untagged fills keys the resource does not carry.'
TBLPROPERTIES ('quality' = 'silver');

-- COMMAND ----------

-- DBTITLE 1,td_tag_key
-- Tag key dimension: one row per distinct tag key observed across jobs, warehouses, pipelines, and clusters.
-- Natural key: tag_key_cd — tag key names are global (workspace-agnostic labels such as AppId, env, team).
CREATE TABLE IF NOT EXISTS global_it_hub.td_tag_key (
  tag_key_id    BIGINT    GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) COMMENT 'Surrogate key — auto-assigned integer for Power BI relationships',
  tag_key_cd    STRING    NOT NULL COMMENT 'Normalized tag key name (e.g. AppId, env, team) — business-facing label',
  raw_key_lb    STRING             COMMENT 'Original tag key as extracted from the resource MAP before normalization (e.g. app_id). Equals tag_key_cd when no normalization applies.',
  -- Audit
  sys_create_dt TIMESTAMP NOT NULL COMMENT 'When this row was first inserted by the pipeline',
  sys_update_dt TIMESTAMP NOT NULL COMMENT 'When this row was last written by the pipeline'
)
USING DELTA
COMMENT 'Tag key dimension. One row per distinct tag key across jobs, warehouses, pipelines, and clusters.'
TBLPROPERTIES ('quality' = 'silver');

-- COMMAND ----------

-- DBTITLE 1,td_tag_key — default rows
MERGE INTO global_it_hub.td_tag_key AS tgt
USING (
  VALUES
    (-2, 'Unassigned', 'Unassigned'),
    (-1, 'Unknown',    'Unknown')
  AS src(tag_key_id, tag_key_cd, raw_key_lb)
) ON tgt.tag_key_id = src.tag_key_id
WHEN NOT MATCHED THEN INSERT (tag_key_id, tag_key_cd, raw_key_lb, sys_create_dt, sys_update_dt)
VALUES (src.tag_key_id, src.tag_key_cd, src.raw_key_lb, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- COMMAND ----------

-- DBTITLE 1,td_workspace
-- Workspace dimension: one row per Databricks workspace. Populated by silver_workspace.sql
-- (MERGE against access_workspaces_latest, a full-overwrite snapshot — not DLT-managed;
-- apply_changes() requires an append-only streaming source, which this table can't provide).
CREATE TABLE IF NOT EXISTS global_it_hub.td_workspace (
  workspace_id      BIGINT    GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) COMMENT 'Surrogate key.',
  account_cd        STRING    NOT NULL COMMENT 'Databricks account UUID.',
  workspace_cd   STRING    NOT NULL COMMENT 'Natural key — system tables workspace_id.',
  workspace_lb STRING    COMMENT 'Workspace display name.',
  workspace_url_lb  STRING    COMMENT 'Workspace URL.',
  create_dt         TIMESTAMP COMMENT 'Workspace creation timestamp.',
  status_lb         STRING    COMMENT 'Workspace status (e.g. RUNNING, CANCELLED).',
  is_deleted_fl     INT       COMMENT 'Flag: 1 if the workspace is absent from the latest access_workspaces_latest snapshot, 0 otherwise.',
  -- Audit
  sys_create_dt     TIMESTAMP NOT NULL COMMENT 'When this row was first inserted',
  sys_update_dt     TIMESTAMP NOT NULL COMMENT 'When this row was last updated'
)
USING DELTA
COMMENT 'Workspace dimension. One row per Databricks workspace.'
TBLPROPERTIES ('quality' = 'silver');

-- COMMAND ----------

-- DBTITLE 1,td_workspace — sentinel rows
MERGE INTO global_it_hub.td_workspace AS tgt
USING (
  VALUES
    (-4, 'Z_DEL',   'Z_DEL',   'Z_Deleted',    'Z_DEL',   'Z_DEL',   0),
    (-3, 'Z_OTHER', 'Z_OTHER', 'Z_Other',      'Z_OTHER', 'Z_OTHER', 0),
    (-2, 'Z_UNS',   'Z_UNS',   'Z_Unassigned', 'Z_UNS',   'Z_UNS',   0),
    (-1, 'Z_UNK',   'Z_UNK',   'Z_Unknown',    'Z_UNK',   'Z_UNK',   0)
  AS src(workspace_id, account_cd, workspace_cd, workspace_lb, workspace_url_lb, status_lb, is_deleted_fl)
) ON tgt.workspace_id = src.workspace_id
WHEN NOT MATCHED THEN INSERT (workspace_id, account_cd, workspace_cd, workspace_lb, workspace_url_lb, create_dt, status_lb, is_deleted_fl, sys_create_dt, sys_update_dt)
VALUES (src.workspace_id, src.account_cd, src.workspace_cd, src.workspace_lb, src.workspace_url_lb, CURRENT_TIMESTAMP(), src.status_lb, src.is_deleted_fl, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- COMMAND ----------

-- DBTITLE 1,td_billing_list_price
-- List price dimension: one row per price validity window (account_cd, sku_name_lb,
-- cloud_lb, currency_code_lb, price_start_dt). No surrogate key — internal join source
-- for tf_billing_cost, not a Power BI-facing dimension. Populated by silver_billing_cost.sql
-- (MERGE against billing_list_prices, a full-overwrite snapshot — not DLT-managed;
-- apply_changes() requires an append-only streaming source, which this table can't provide).
CREATE TABLE IF NOT EXISTS global_it_hub.td_billing_list_price (
  account_cd              STRING    NOT NULL COMMENT 'Databricks account UUID.',
  sku_name_lb             STRING    NOT NULL COMMENT 'Billing SKU name.',
  cloud_lb                STRING    NOT NULL COMMENT 'Cloud provider: AWS, AZURE, or GCP.',
  currency_code_lb        STRING    NOT NULL COMMENT 'Price currency code (e.g. USD).',
  usage_unit_lb           STRING             COMMENT 'Unit of measurement, e.g. DBU.',
  default_price_nb        DOUBLE             COMMENT 'Default list price per usage unit.',
  effective_list_price_nb DOUBLE             COMMENT 'Contracted/effective list price per usage unit, when different from default.',
  price_start_dt          TIMESTAMP NOT NULL COMMENT 'Start of this price validity window — part of the natural key.',
  price_end_dt            TIMESTAMP          COMMENT 'End of this price validity window, or NULL if still current.',
  -- Audit
  sys_create_dt           TIMESTAMP NOT NULL COMMENT 'When this row was first inserted',
  sys_update_dt           TIMESTAMP NOT NULL COMMENT 'When this row was last updated'
)
USING DELTA
COMMENT 'Billing list price dimension. One row per price validity window. Internal join source for tf_billing_cost.'
TBLPROPERTIES ('quality' = 'silver');

-- COMMAND ----------

-- DBTITLE 1,td_dbx_user
-- User dimension: one row per SCIM user. Populated by silver_identity.sql (MERGE against
-- account_users, upserted with soft-delete by an Account API export job — not DLT-managed;
-- apply_changes() requires an append-only streaming source, which a row-level upsert can't
-- provide). is_active_fl folds in the source's soft-delete (deleted_at IS NULL check).
CREATE TABLE IF NOT EXISTS global_it_hub.td_dbx_user (
  user_id          BIGINT    GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) COMMENT 'Surrogate key.',
  account_cd       STRING    COMMENT 'Databricks account UUID.',
  user_cd       STRING    NOT NULL COMMENT 'Natural key — SCIM user ID.',
  username_lb      STRING    COMMENT 'User login name.',
  display_name_lb  STRING    COMMENT 'User display name.',
  first_name_lb    STRING    COMMENT 'User first name.',
  last_name_lb     STRING    COMMENT 'User last name.',
  is_active_fl     INT       COMMENT 'Flag: 1 if the user is active, 0 otherwise (includes soft-deleted).',
  external_cd   STRING    COMMENT 'External identity provider ID.',
  primary_email_lb STRING    COMMENT 'User primary email address.',
  -- Audit
  sys_create_dt    TIMESTAMP NOT NULL COMMENT 'When this row was first inserted (source: first_seen_at)',
  sys_update_dt    TIMESTAMP NOT NULL COMMENT 'When this row was last updated (source: last_seen_at)'
)
USING DELTA
COMMENT 'User dimension. One row per SCIM user.'
TBLPROPERTIES ('quality' = 'silver');

-- COMMAND ----------

-- DBTITLE 1,td_dbx_user — sentinel rows
MERGE INTO global_it_hub.td_dbx_user AS tgt
USING (
  VALUES
    (-2, 'UNS', 'UNS', 'Unassigned', 'Unassigned', 'Unassigned', 'Unassigned', 0, 'UNS', 'UNS'),
    (-1, 'UNK', 'UNK', 'Unknown',    'Unknown',    'Unknown',    'Unknown',    0, 'UNK', 'UNK')
  AS src(user_id, account_cd, user_cd, username_lb, display_name_lb, first_name_lb, last_name_lb, is_active_fl, external_cd, primary_email_lb)
) ON tgt.user_id = src.user_id
WHEN NOT MATCHED THEN INSERT (user_id, account_cd, user_cd, username_lb, display_name_lb, first_name_lb, last_name_lb, is_active_fl, external_cd, primary_email_lb, sys_create_dt, sys_update_dt)
VALUES (src.user_id, src.account_cd, src.user_cd, src.username_lb, src.display_name_lb, src.first_name_lb, src.last_name_lb, src.is_active_fl, src.external_cd, src.primary_email_lb, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- COMMAND ----------

-- DBTITLE 1,td_dbx_service_principal
-- Service principal dimension: one row per SCIM service principal. Populated by
-- silver_identity.sql (MERGE against account_service_principals, upserted with soft-delete by
-- an Account API export job — not DLT-managed, same reasoning as td_dbx_user).
CREATE TABLE IF NOT EXISTS global_it_hub.td_dbx_service_principal (
  sp_id             BIGINT    GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) COMMENT 'Surrogate key.',
  account_cd        STRING    COMMENT 'Databricks account UUID.',
  sp_cd          STRING    NOT NULL COMMENT 'Natural key — SCIM service principal ID.',
  application_cd STRING    COMMENT 'Service principal application (client) ID.',
  display_name_lb   STRING    COMMENT 'Service principal display name.',
  is_active_fl      INT       COMMENT 'Flag: 1 if the service principal is active, 0 otherwise (includes soft-deleted).',
  external_cd    STRING    COMMENT 'External identity provider ID.',
  -- Audit
  sys_create_dt     TIMESTAMP NOT NULL COMMENT 'When this row was first inserted (source: first_seen_at)',
  sys_update_dt     TIMESTAMP NOT NULL COMMENT 'When this row was last updated (source: last_seen_at)'
)
USING DELTA
COMMENT 'Service principal dimension. One row per SCIM service principal.'
TBLPROPERTIES ('quality' = 'silver');

-- COMMAND ----------

-- DBTITLE 1,td_dbx_service_principal — sentinel rows
MERGE INTO global_it_hub.td_dbx_service_principal AS tgt
USING (
  VALUES
    (-2, 'UNS', 'UNS', 'UNS', 'Unassigned', 0, 'UNS'),
    (-1, 'UNK', 'UNK', 'UNK', 'Unknown',    0, 'UNK')
  AS src(sp_id, account_cd, sp_cd, application_cd, display_name_lb, is_active_fl, external_cd)
) ON tgt.sp_id = src.sp_id
WHEN NOT MATCHED THEN INSERT (sp_id, account_cd, sp_cd, application_cd, display_name_lb, is_active_fl, external_cd, sys_create_dt, sys_update_dt)
VALUES (src.sp_id, src.account_cd, src.sp_cd, src.application_cd, src.display_name_lb, src.is_active_fl, src.external_cd, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- COMMAND ----------

-- DBTITLE 1,td_identity
-- Unified identity dimension: one row per user or service principal. Populated by
-- silver_identity.sql from the same staged sources as td_dbx_user/td_dbx_service_principal — not
-- DLT-managed, same reasoning.
CREATE TABLE IF NOT EXISTS global_it_hub.td_identity (
  identity_id       BIGINT    GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) COMMENT 'Surrogate key.',
  account_cd        STRING    NOT NULL COMMENT 'Databricks account UUID.',
  source_cd      STRING    NOT NULL COMMENT 'Natural key — user_cd or sp_cd of the source identity.',
  identity_type_lb  STRING    NOT NULL COMMENT 'Identity type — USER or SERVICE PRINCIPAL.',
  display_name_lb   STRING    COMMENT 'Identity display name.',
  identity_cd    STRING    COMMENT 'Natural login identifier — username for users, application (client) ID for service principals. Joins billing usage run_as_cd.',
  first_name_lb     STRING    COMMENT 'User first name (NULL for service principals).',
  last_name_lb      STRING    COMMENT 'User last name (NULL for service principals).',
  primary_email_lb  STRING    COMMENT 'User primary email address (NULL for service principals).',
  is_active_fl      INT       COMMENT 'Flag: 1 if the identity is active, 0 otherwise (includes soft-deleted).',
  external_cd    STRING    COMMENT 'External identity provider ID.',
  -- Audit
  sys_create_dt     TIMESTAMP NOT NULL COMMENT 'When this row was first inserted (source: first_seen_at)',
  sys_update_dt     TIMESTAMP NOT NULL COMMENT 'When this row was last updated (source: last_seen_at)'
)
USING DELTA
COMMENT 'Unified identity dimension. One row per user or service principal.'
TBLPROPERTIES ('quality' = 'silver');

-- COMMAND ----------

-- DBTITLE 1,td_identity — sentinel rows
MERGE INTO global_it_hub.td_identity AS tgt
USING (
  VALUES
    (-6, 'Z_OTHER', 'Z_OTHER',           'Z_DEL',          'Deleted Identity',          'Z_DEL',          'Z_DEL',          'Z_DEL',          'Z_DEL',          0, 'Z_DEL'),
    (-5, 'Z_OTHER', 'Z_OTHER',           'Z_OTHER',        'Other Identity',            'Z_OTHER',        'Z_OTHER',        'Z_OTHER',        'Z_OTHER',        0, 'Z_OTHER'),
    (-4, 'Z_OTHER', 'SERVICE PRINCIPAL', 'Z_UNKNOWN_SP',   'Unknown Service Principal', 'Z_UNKNOWN_SP',   'Z_UNKNOWN_SP',   'Z_UNKNOWN_SP',   'Z_UNKNOWN_SP',   0, 'Z_UNKNOWN_SP'),
    (-3, 'Z_OTHER', 'USER',              'Z_UNKNOWN_USER', 'Unknown User',              'Z_UNKNOWN_USER', 'Z_UNKNOWN_USER', 'Z_UNKNOWN_USER', 'Z_UNKNOWN_USER', 0, 'Z_UNKNOWN_USER'),
    (-2, 'Z_OTHER', 'Z_OTHER',           'Z_UNS',          'Unassigned Identity',       'Z_UNS',          'Z_UNS',          'Z_UNS',          'Z_UNS',          0, 'Z_UNS'),
    (-1, 'Z_OTHER', 'Z_OTHER',           'Z_UNK',          'Unknown Identity',          'Z_UNK',          'Z_UNK',          'Z_UNK',          'Z_UNK',          0, 'Z_UNK'),
    (0,  'Z_OTHER', 'USER',              'System-User',    'System User',               'Z_SYSTEM_USER',  'Z_SYSTEM_USER',  'Z_SYSTEM_USER',  'Z_SYSTEM_USER',  1, 'Z_SYSTEM_USER')
  AS src(identity_id, account_cd, identity_type_lb, source_cd, display_name_lb, identity_cd, first_name_lb, last_name_lb, primary_email_lb, is_active_fl, external_cd)
) ON tgt.identity_id = src.identity_id
WHEN NOT MATCHED THEN INSERT (identity_id, account_cd, identity_type_lb, source_cd, display_name_lb, identity_cd, first_name_lb, last_name_lb, primary_email_lb, is_active_fl, external_cd, sys_create_dt, sys_update_dt)
VALUES (src.identity_id, src.account_cd, src.identity_type_lb, src.source_cd, src.display_name_lb, src.identity_cd, src.first_name_lb, src.last_name_lb, src.primary_email_lb, src.is_active_fl, src.external_cd, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- COMMAND ----------

-- DBTITLE 1,td_dbx_group
-- Group dimension: one row per SCIM group. Populated by silver_identity.sql from
-- account_groups — not DLT-managed, same reasoning as td_dbx_user/td_dbx_service_principal (row-level
-- upsert + soft-delete source, not append-only).
CREATE TABLE IF NOT EXISTS global_it_hub.td_dbx_group (
  group_id         BIGINT    GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) COMMENT 'Surrogate key.',
  account_cd       STRING    COMMENT 'Databricks account UUID.',
  group_cd         STRING    NOT NULL COMMENT 'Natural key — SCIM group ID.',
  display_name_lb  STRING    COMMENT 'Group display name.',
  is_active_fl     INT       COMMENT 'Flag: 1 if not soft-deleted, 0 otherwise. Groups have no SCIM active attribute, unlike users/service principals — derived from deleted_at only.',
  -- Audit
  sys_create_dt    TIMESTAMP NOT NULL COMMENT 'When this row was first inserted (source: first_seen_at)',
  sys_update_dt    TIMESTAMP NOT NULL COMMENT 'When this row was last updated (source: last_seen_at)'
)
USING DELTA
COMMENT 'Group dimension. One row per SCIM group.'
TBLPROPERTIES ('quality' = 'silver');

-- COMMAND ----------

-- DBTITLE 1,td_dbx_group — sentinel rows
MERGE INTO global_it_hub.td_dbx_group AS tgt
USING (
  VALUES
    (-2, 'Z_OTHER', 'Z_UNS', 'Unassigned Group', 0),
    (-1, 'Z_OTHER', 'Z_UNK', 'Unknown Group',    0)
  AS src(group_id, account_cd, group_cd, display_name_lb, is_active_fl)
) ON tgt.group_id = src.group_id
WHEN NOT MATCHED THEN INSERT (group_id, account_cd, group_cd, display_name_lb, is_active_fl, sys_create_dt, sys_update_dt)
VALUES (src.group_id, src.account_cd, src.group_cd, src.display_name_lb, src.is_active_fl, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- COMMAND ----------

-- DBTITLE 1,tr_dbx_group_member
-- Group membership bridge: one row per (group, member) SCIM edge, exploded from
-- account_groups.raw.members. Populated by silver_identity.sql. member_cd may reference a
-- user, service principal, or another (nested) group, depending on member_type_lb — resolve
-- against td_dbx_user/td_dbx_service_principal/td_dbx_group downstream using member_type_lb as the
-- discriminator. Natural-key bridge (not surrogate FK bigints like tr_resource_tag) since
-- members span three different dimension tables.
CREATE TABLE IF NOT EXISTS global_it_hub.tr_dbx_group_member (
  account_cd     STRING NOT NULL COMMENT 'Databricks account UUID.',
  group_cd       STRING NOT NULL COMMENT 'Natural key — SCIM group ID (td_dbx_group.group_cd) that owns this membership.',
  member_cd      STRING NOT NULL COMMENT 'Natural key — SCIM ID of the member, parsed from the last segment of the SCIM $ref path.',
  member_type_lb STRING NOT NULL COMMENT 'Member principal type parsed from the SCIM $ref path prefix — Users, ServicePrincipals, or Groups.',
  is_deleted_fl  INT    COMMENT 'Flag: 1 if this membership is absent from the latest account_groups snapshot (member removed, or its group soft-deleted), 0 otherwise.',
  -- Audit
  sys_create_dt  TIMESTAMP NOT NULL COMMENT 'When this row was first inserted by the pipeline',
  sys_update_dt  TIMESTAMP NOT NULL COMMENT 'When this row was last written by the pipeline'
)
USING DELTA
COMMENT 'Group membership bridge. One row per (group, member) edge from SCIM group raw payload.'
TBLPROPERTIES ('quality' = 'silver');

-- COMMAND ----------

-- DBTITLE 1,tr_dbx_user_security
-- User security bridge: for each user, the flattened set of users/service principals they
-- share visibility with — themselves, direct co-members of every group they belong to, and
-- members of any group nested (recursively, to arbitrary depth) inside those groups.
-- Populated by silver_user_security.sql via MERGE with no WHEN MATCHED branch: the
-- (user_cd, member_cd) key is the whole row, so a matched pair is left untouched — sys_create_dt
-- preserves "when did this visibility relationship first appear" (access-review value). No
-- is_deleted_fl — WHEN NOT MATCHED BY SOURCE THEN DELETE is a hard delete; a row's absence from
-- the freshly recomputed source IS the delete signal.
-- Natural-key bridge (not surrogate FK bigints) — member_cd may resolve against either
-- td_dbx_user or td_dbx_service_principal depending on principal type; join on identity_cd equivalents.
CREATE TABLE IF NOT EXISTS global_it_hub.tr_dbx_user_security (
  user_cd       STRING    NOT NULL COMMENT 'Natural key — td_dbx_user.user_cd of the acting/viewing user.',
  member_cd     STRING    NOT NULL COMMENT 'Natural key — SCIM ID (user or service principal) visible to user_cd. Equals user_cd for the self row.',
  -- Audit
  sys_create_dt TIMESTAMP NOT NULL COMMENT 'When this visibility relationship was first discovered',
  sys_update_dt TIMESTAMP NOT NULL COMMENT 'When this row was last written by the pipeline'
)
USING DELTA
COMMENT 'User security bridge. One row per (user, visible member) pair, flattened through recursive group nesting. Full-overwrite table.'
TBLPROPERTIES ('quality' = 'silver');

-- COMMAND ----------

-- DBTITLE 1,td_resource
-- Unified resource dimension: one row per billable resource (job, pipeline, cluster,
-- warehouse, app, notebook, endpoint, networking client), unioning 8 silver dimension
-- tables. Populated by silver_resource.sql — not DLT-managed; every one of those 8 source
-- tables is itself apply_changes()-managed (SCD1) and receives row-level UPDATEs, which a
-- streaming UNION can't tolerate (DELTA_SOURCE_TABLE_IGNORE_CHANGES the moment any source
-- row changes) without silently dropping updates via skipChangeCommits. Same reasoning as
-- td_workspace/td_billing_list_price/td_identity.
CREATE TABLE IF NOT EXISTS global_it_hub.td_resource (
  resource_id      BIGINT    GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) COMMENT 'Surrogate key.',
  resource_type_lb STRING    NOT NULL COMMENT 'Resource type — JOB, PIPELINE, WAREHOUSE, CLUSTER, APP, NOTEBOOK, ENDPOINT, NETWORKING, DATA_QUALITY_MONITORING, or the product label.',
  source_cd        STRING    NOT NULL COMMENT 'Natural key — source system ID of the resource (e.g. job_cd, cluster_cd).',
  account_cd       STRING    NOT NULL COMMENT 'Databricks account UUID.',
  region_lb        STRING    COMMENT 'Databricks region (e.g. eastus, westeurope).',
  workspace_cd     STRING    NOT NULL COMMENT 'Workspace ID the resource belongs to.',
  display_name_lb  STRING    COMMENT 'Resource display name.',
  owned_by_cd      STRING    COMMENT 'User or service principal ID that owns the resource.',
  is_active_fl     INT       COMMENT 'Flag: 1 if the resource is active, 0 otherwise.',
  -- Audit
  sys_create_dt    TIMESTAMP NOT NULL COMMENT 'When this row was first inserted',
  sys_update_dt    TIMESTAMP NOT NULL COMMENT 'When this row was last updated'
)
USING DELTA
COMMENT 'Unified resource dimension. One row per billable resource.'
TBLPROPERTIES ('quality' = 'silver');

-- COMMAND ----------

-- DBTITLE 1,td_resource — sentinel rows
MERGE INTO global_it_hub.td_resource AS tgt
USING (
  VALUES
    -- Per-type unknown sentinels: one row per resource_type_lb handled by v_resource_union
    (-11, 'DATA QUALITY MONITORING', 'Z_UNKNOWN_DQM', 'Z_UNKNOWN', 'Z_UNKNOWN', 'Unknown Data Quality Monitoring', 'Z_UNKNOWN', 0),
    (-10, 'NETWORKING', 'Z_UNKNOWN_NETWORKING', 'Z_UNKNOWN', 'Z_UNKNOWN', 'Unknown Networking', 'Z_UNKNOWN', 0),
    (-9,  'ENDPOINT',   'Z_UNKNOWN_ENDPOINT',   'Z_UNKNOWN', 'Z_UNKNOWN', 'Unknown Endpoint',   'Z_UNKNOWN', 0),
    (-8,  'NOTEBOOK',   'Z_UNKNOWN_NOTEBOOK',   'Z_UNKNOWN', 'Z_UNKNOWN', 'Unknown Notebook',   'Z_UNKNOWN', 0),
    (-7,  'APP',        'Z_UNKNOWN_APP',        'Z_UNKNOWN', 'Z_UNKNOWN', 'Unknown App',        'Z_UNKNOWN', 0),
    (-6,  'WAREHOUSE',  'Z_UNKNOWN_WAREHOUSE',  'Z_UNKNOWN', 'Z_UNKNOWN', 'Unknown Warehouse',  'Z_UNKNOWN', 0),
    (-5,  'CLUSTER',    'Z_UNKNOWN_CLUSTER',    'Z_UNKNOWN', 'Z_UNKNOWN', 'Unknown Cluster',    'Z_UNKNOWN', 0),
    (-4,  'PIPELINE',   'Z_UNKNOWN_PIPELINE',   'Z_UNKNOWN', 'Z_UNKNOWN', 'Unknown Pipeline',   'Z_UNKNOWN', 0),
    (-3,  'JOB',        'Z_UNKNOWN_JOB',        'Z_UNKNOWN', 'Z_UNKNOWN', 'Unknown Job',        'Z_UNKNOWN', 0),
    -- Generic cross-type sentinels
    (-2,  'Z_OTHER',    'Z_UNDEFINED', 'Z_OTHER', 'Z_OTHER',  'Unassigned Resource', 'Z_OTHER', 0),
    (-1,  'Z_OTHER',    'Z_UNKNOWN',   'Z_OTHER', 'Z_OTHER',  'Unknown Resource',    'Z_OTHER', 0),
    (0,   'Z_OTHER',    'Z_OTHER',     'Z_OTHER', 'Z_OTHER',  'Other Resource',      'Z_OTHER', 0)
  AS src(resource_id, resource_type_lb, source_cd, account_cd, workspace_cd, display_name_lb, owned_by_cd, is_active_fl)
) ON tgt.resource_id = src.resource_id
WHEN NOT MATCHED THEN INSERT (resource_id, resource_type_lb, source_cd, account_cd, workspace_cd, display_name_lb, owned_by_cd, is_active_fl, sys_create_dt, sys_update_dt)
VALUES (src.resource_id, src.resource_type_lb, src.source_cd, src.account_cd, src.workspace_cd, src.display_name_lb, src.owned_by_cd, src.is_active_fl, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

