-- Databricks notebook source
-- DBTITLE 1,Notebook Summary
-- MAGIC %md
-- MAGIC ## Silver — Resource Dimension (Unified, SCD1)
-- MAGIC
-- MAGIC Builds `td_resource` — one row per billable resource (job, pipeline, cluster, warehouse,
-- MAGIC app, notebook, endpoint, networking client, data quality monitoring schema) — from a
-- MAGIC `UNION ALL` of 11 branches (ENDPOINT resources come from two source tables,
-- MAGIC `td_serving_entity` and `td_billing_endpoint`, deduplicated — see below).
-- MAGIC
-- MAGIC **Not DLT-managed** — moved off `apply_changes()`/streaming (`silver_dimensions.py`)
-- MAGIC because every source table (`td_lakeflow_job`, `td_compute_warehouse`,
-- MAGIC `td_lakeflow_pipeline`, `td_compute_cluster`, `td_billing_app`, `td_billing_notebook`,
-- MAGIC `td_billing_endpoint`, `td_billing_network`, `td_billing_data_quality_monitoring`,
-- MAGIC `td_serving_entity`) is itself
-- MAGIC `apply_changes()`-managed (SCD1) and receives row-level UPDATEs whenever an attribute
-- MAGIC changes — not append-only. A streaming read of an upserted table fails with
-- MAGIC `DELTA_SOURCE_TABLE_IGNORE_CHANGES` the moment any row is updated; the only
-- MAGIC streaming-safe workaround (`skipChangeCommits`) would silently drop every such update
-- MAGIC forever, leaving `td_resource` permanently stale. Same reasoning as
-- MAGIC `td_workspace`/`td_billing_list_price`/`td_identity`.
-- MAGIC
-- MAGIC | Source | Target |
-- MAGIC |---|---|
-- MAGIC | 11 silver dimension tables (`UNION ALL`) | `global_it_hub.td_resource` |
-- MAGIC
-- MAGIC **Prerequisites**: run the silver DLT pipeline first — all 11 source tables must be
-- MAGIC populated.
-- MAGIC
-- MAGIC ### Processing strategy
-- MAGIC No watermark: every run re-reads all 11 source tables in full (each is already a small
-- MAGIC current-state SCD1 dimension, not a growing fact table — cheap to rescan) and MERGEs
-- MAGIC into `td_resource`. `resource_id` is preserved on UPDATE (Delta `GENERATED BY DEFAULT AS
-- MAGIC IDENTITY`, omitted from the INSERT column list — auto-assigned only for genuinely new
-- MAGIC resources). `is_active_fl` mirrors each source's `is_deleted_fl` where available (jobs,
-- MAGIC warehouses, pipelines, clusters, and now the `td_serving_entity` branch of ENDPOINT);
-- MAGIC billing dimensions without a deletion concept upstream (apps, notebooks, the
-- MAGIC `td_billing_endpoint` fallback branch of ENDPOINT, networking, data quality monitoring,
-- MAGIC predictive optimization) are always active.
-- MAGIC
-- MAGIC **ENDPOINT resources come from two sources, deduplicated by `endpoint_cd`**:
-- MAGIC `td_serving_entity` (richer — real `region_lb`/`is_deleted_fl`, from
-- MAGIC `system.serving.served_entities`, collapsed from served-entity grain to endpoint grain
-- MAGIC with `QUALIFY ROW_NUMBER() ... ORDER BY change_time DESC = 1`) is the primary source;
-- MAGIC `td_billing_endpoint` (from billing usage) only contributes an endpoint via `NOT EXISTS`
-- MAGIC when `td_serving_entity` doesn't already have it — covers endpoints that generated
-- MAGIC billing usage but haven't (yet) appeared in the serving system table.
-- MAGIC
-- MAGIC Each branch filters `WHERE {entity}_id > 0` to exclude the -2/-1 sentinel rows
-- MAGIC (Unassigned/Unknown) from each source dimension — `td_resource` has its own sentinel
-- MAGIC rows (inserted via `init_tables_silver.sql`) and must not union in the sources'.

-- COMMAND ----------

-- MAGIC %python
-- MAGIC dbutils.widgets.text("catalog_env", "dev")
-- MAGIC catalog_env = dbutils.widgets.get("catalog_env")
-- MAGIC
-- MAGIC dbutils.widgets.text("catalog_name", "it_security")
-- MAGIC catalog_name = dbutils.widgets.get("catalog_name")
-- MAGIC
-- MAGIC catalog = f"{catalog_name}_{catalog_env}"
-- MAGIC silver_schema = "global_it_hub"
-- MAGIC
-- MAGIC spark.sql(f"USE CATALOG {catalog}")
-- MAGIC spark.sql(f"USE SCHEMA {silver_schema}")
-- MAGIC
-- MAGIC print(f"Catalog : {catalog}")
-- MAGIC print(f"Schema  : {silver_schema}")

-- COMMAND ----------

-- DBTITLE 1,Step 1 — Stage unified resource union (9 dimension tables)
-- UNION ALL matches columns by position, not name — every branch must list columns in the
-- exact same order. Referenced once (Step 2) — temp view, not materialized.
CREATE OR REPLACE TEMP VIEW v_resource_union AS

SELECT
  'JOB'              AS resource_type_lb,
  job_cd             AS source_cd,
  account_cd,
  region_lb,
  workspace_cd,
  job_name_lb        AS display_name_lb,
  creator_userid_cd  AS owned_by_cd,
  CASE WHEN is_deleted_fl = 0 THEN 1 ELSE 0 END AS is_active_fl
FROM global_it_hub.td_lakeflow_job
WHERE job_id > 0

UNION ALL

SELECT
  'WAREHOUSE'        AS resource_type_lb,
  warehouse_cd       AS source_cd,
  account_cd,
  region_lb,
  workspace_cd,
  warehouse_name_lb  AS display_name_lb,
  created_by_cd      AS owned_by_cd,
  CASE WHEN is_deleted_fl = 0 THEN 1 ELSE 0 END AS is_active_fl
FROM global_it_hub.td_compute_warehouse
WHERE warehouse_id > 0

UNION ALL

SELECT
  'PIPELINE'         AS resource_type_lb,
  pipeline_cd        AS source_cd,
  account_cd,
  region_lb,
  workspace_cd,
  pipeline_name_lb   AS display_name_lb,
  created_by_cd      AS owned_by_cd,
  CASE WHEN is_deleted_fl = 0 THEN 1 ELSE 0 END AS is_active_fl
FROM global_it_hub.td_lakeflow_pipeline
WHERE pipeline_id > 0

UNION ALL

SELECT
  'CLUSTER'          AS resource_type_lb,
  cluster_cd         AS source_cd,
  account_cd,
  region_lb,
  workspace_cd,
  cluster_name_lb    AS display_name_lb,
  owned_by_cd,
  CASE WHEN is_deleted_fl = 0 THEN 1 ELSE 0 END AS is_active_fl
FROM global_it_hub.td_compute_cluster
WHERE cluster_id > 0

UNION ALL

-- Billing dimensions have no region field (use 'global') and no deletion concept (always active).
SELECT
  'APP'              AS resource_type_lb,
  app_cd             AS source_cd,
  account_cd,
  'global'           AS region_lb,
  workspace_cd,
  app_name_lb        AS display_name_lb,
  run_as_cd          AS owned_by_cd,
  1                  AS is_active_fl
FROM global_it_hub.td_billing_app
WHERE app_id > 0

UNION ALL

SELECT
  'NOTEBOOK'         AS resource_type_lb,
  notebook_cd        AS source_cd,
  account_cd,
  'global'           AS region_lb,
  workspace_cd,
  notebook_path_lb   AS display_name_lb,
  run_as_cd          AS owned_by_cd,
  1                  AS is_active_fl
FROM global_it_hub.td_billing_notebook
WHERE notebook_id > 0

UNION ALL

-- Primary source of ENDPOINT resources: td_serving_entity (system.serving.served_entities)
-- collapsed from served-entity grain to endpoint grain — has a real region_lb and
-- is_deleted_fl, unlike td_billing_endpoint. QUALIFY keeps only the most recently changed
-- served entity per endpoint; region_lb/is_deleted_fl are genuinely endpoint-level fields
-- (uniform across every served entity of that endpoint), so picking any one row is safe.
SELECT
  'ENDPOINT'         AS resource_type_lb,
  endpoint_cd        AS source_cd,
  account_cd,
  region_lb,
  workspace_cd,
  endpoint_name_lb   AS display_name_lb,
  created_by_cd      AS owned_by_cd,
  CASE WHEN is_deleted_fl = 0 THEN 1 ELSE 0 END AS is_active_fl
FROM global_it_hub.td_serving_entity
WHERE entity_id > 0
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY account_cd, workspace_cd, endpoint_cd
  ORDER BY change_time DESC
) = 1

UNION ALL

-- Fallback source of ENDPOINT resources: td_billing_endpoint only contributes endpoints not
-- already captured by td_serving_entity (e.g. endpoints with billing usage but not yet seen
-- by system.serving.served_entities) — avoids duplicate ENDPOINT rows for the same endpoint_cd.
SELECT
  'ENDPOINT'         AS resource_type_lb,
  t1.endpoint_cd     AS source_cd,
  t1.account_cd,
  'global'           AS region_lb,
  t1.workspace_cd,
  t1.endpoint_name_lb AS display_name_lb,
  t1.run_as_cd       AS owned_by_cd,
  1                  AS is_active_fl
FROM global_it_hub.td_billing_endpoint AS t1
WHERE t1.endpoint_id > 0
  AND NOT EXISTS (
    SELECT 1
    FROM global_it_hub.td_serving_entity AS t2
    WHERE t2.entity_id     > 0
      AND t2.account_cd    = t1.account_cd
      AND t2.workspace_cd  = t1.workspace_cd
      AND t2.endpoint_cd   = t1.endpoint_cd
  )

UNION ALL

SELECT
  'NETWORKING'       AS resource_type_lb,
  network_client_cd  AS source_cd,
  account_cd,
  'global'           AS region_lb,
  workspace_cd,
  network_client_cd  AS display_name_lb,
  run_as_cd          AS owned_by_cd,
  1                  AS is_active_fl
FROM global_it_hub.td_billing_network
WHERE network_id > 0

UNION ALL

SELECT
  'DATA QUALITY MONITORING' AS resource_type_lb,
  dqm_cd             AS source_cd,
  account_cd,
  'global'           AS region_lb,
  workspace_cd,
  dqm_cd             AS display_name_lb,
  created_by_cd      AS owned_by_cd,
  1                  AS is_active_fl
FROM global_it_hub.td_billing_data_quality_monitoring
WHERE dqm_id > 0

UNION ALL
SELECT
  'PREDICTIVE OPTIMIZATION' AS resource_type_lb,
  'PREDICTIVE_OPTIMIZATION' AS source_cd,
  account_cd,
  'global'           AS region_lb,
  workspace_cd,
  'Predictive Optimization'  AS display_name_lb,
  'System-User'      AS owned_by_cd,
  1                  AS is_active_fl
FROM global_it_hub.td_workspace
WHERE workspace_id > 0;

-- COMMAND ----------

-- DBTITLE 1,Step 2 — Upsert td_resource
-- Merge key: (account_cd, workspace_cd, source_cd, resource_type_lb) — same key the old
-- apply_changes() used, so resource_id stays stable across the DLT-to-MERGE migration.
-- resource_id is Delta GENERATED BY DEFAULT AS IDENTITY — omitted from INSERT, auto-assigned
-- for new rows; preserved on UPDATE by never being written to.
MERGE INTO global_it_hub.td_resource AS tgt
USING v_resource_union AS src
  ON  tgt.account_cd       = src.account_cd
  AND tgt.workspace_cd     = src.workspace_cd
  AND tgt.source_cd        = src.source_cd
  AND tgt.resource_type_lb = src.resource_type_lb
WHEN MATCHED AND (
     tgt.region_lb        IS DISTINCT FROM src.region_lb
  OR tgt.display_name_lb  IS DISTINCT FROM src.display_name_lb
  OR tgt.owned_by_cd      IS DISTINCT FROM src.owned_by_cd
  OR tgt.is_active_fl     IS DISTINCT FROM src.is_active_fl
) THEN UPDATE SET
  tgt.region_lb       = src.region_lb,
  tgt.display_name_lb = src.display_name_lb,
  tgt.owned_by_cd     = src.owned_by_cd,
  tgt.is_active_fl    = src.is_active_fl,
  tgt.sys_update_dt   = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  resource_type_lb, source_cd, account_cd, region_lb, workspace_cd,
  display_name_lb, owned_by_cd, is_active_fl, sys_create_dt, sys_update_dt
) VALUES (
  src.resource_type_lb, src.source_cd, src.account_cd, src.region_lb, src.workspace_cd,
  src.display_name_lb, src.owned_by_cd, src.is_active_fl, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);
